### ISSUE TITLE
Fatal error if a ViewHelper is not correctly-cased

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3Fluid/Fluid#9] opened 2015-09-23 11:39 UTC
When referring to a ViewHelper without using the right camelCasing, a fatal error is triggered.
See https://jira.neos.io/browse/FLOW-152 for a related fix that improved handling of those cases.

## Template

the ViewHelper is called FlashMessagesViewHelper, with an uppercase M

```html
<f:flashmessages />
```
## Expected output

```
The ViewHelper "<f:flashmessages>" inside your template is not written correctly upper/lowercased.
Based on your spelling, the system would load the (non-existant) class "TYPO3\Fluid\ViewHelpers\FlashmessagesViewHelper", however the real class name is "TYPO3\Fluid\ViewHelpers\FlashMessagesViewHelper".
This error can be fixed by making sure the ViewHelper is written in the correct upper/lowercase form.
```

## Actual output

```
Fatal error: Call to a member function getMethodParameters() on null in AbstractViewHelper.php on line 208
```

**Comment by NamelessCoder** [comment] 2015-09-23 13:30
Hmm - I believe this one should be solved by throwing an Exception in (adapter's) ViewHelperResolver when whichever class loader is used, returns `null` instead of an instance (and doesn't report that it couldn't load the class). This would also allow the Exception to be specific; caused by an actually missing class or an in-included namespace (see also https://github.com/TYPO3Fluid/Fluid/issues/8#issuecomment-142598942)

**Comment by NamelessCoder** [comment] 2015-10-11 12:49
@bwaidelich If you have the time would you mind throwing your two cents in here? I personally don't think we should be doing this - PHP classes aren't case sensitive - but of course I recognise that it would cause issues in Flow. However: I would argue that this is because Flow imposes the class name case sensitivity through the use of things like Reflection and AOP that stores entries using the class name as input *without also homogenising (read: lowercasing) the generated indexes, compound classes and such*.

You can probably already tell from this that rather than forcing Fluid to impose this same class name sensitivity restriction as Flow does (which is contrary to PHP nature), the sensible way to solve this one would be to either make Flow report an error if some class name was incorrectly cased (as suggested in the issue you link to), or make Flow case insensitive when it comes to anything related to generated classes (as suggested by how PHP in general works).

Which ultimately means that I'd advise we reject this.

**Comment by bwaidelich** [comment] 2015-10-20 12:32
I don't think that this has to do with PHPs ([questionable](https://bugs.php.net/bug.php?id=15415)) nature of dealing with case sensitivity to be honest.
Personally I think it's a good habit to follow the strict casing and show a helpful error if it's wrong according to the *fail early, fail often* paradigm. At least that's how Fluid does it currently.

But sure, if that behavior is about to be dropped with the standalone version we can probably re-enforce it via the adapter in Flow.
Right now we get a Fatal Error. But if that's not the case in standalone (and CMS) we can certainly fix that in the adapter

**Comment by NamelessCoder** [comment] 2015-10-20 12:49
> Personally I think it's a good habit to follow the strict casing and show a helpful error if it's wrong according to the fail early, fail often paradigm.

It's *technically* not a reason for failure; but that's because PHP is a bit silly there. Any class loader on a case sensitive file system would care, but that doesn't mean that *we* must enforce it ;)

All we should be doing is assume that classes can be loaded under the normal premises for PHP using composer autoloading - and then make it up to each implementer if the *way* that Fluid's classes get used doesn't play well (e.g. the fatal error in Flow when attempting to build proxy classes with a name that doesn't match the one used to load the class) with the class loading of choice.

As a CMS-specific tidbit of information I can tell you that Helmut's alias class loader has a toggle that affects the behavior re: case sensitivity when loading aliased classes - and it does so by manipulating the alias registrations into forcing a lowercase name also when registering and loading aliased classes. CMS will throw a "ViewHelper not found" exception on mis-cased class names if you're using a case sensitive file system - and won't if you're not (works without failing).

**Comment by bwaidelich** [comment] 2016-04-01 12:01
You asked for feedback on this one, but I'm not sure how to continue with that because it seems we're talking cross purpose. I didn't mean to start a discussion about PHPs handling of case sensitivity as mentioned. IMO this is just about the behavior of a DSL (in this case Fluid templates) which changed.

I'm not saying any one of the two ways is better but we have to
a) Change it in TYPO3Fluid
b) Introduce a breaking change
c) Adjust the behavior in the adapter

the latter is probably the most feasible for the moment.
So feel free to close this one but it must not be forgotten when the adapter is implemented.

**Comment by NamelessCoder** [comment] 2016-07-12 11:07
I'll close this one and mention @kitsunet since he is doing work on the Flow adapter - and await any feedback that may come, about whether or not we also need to change TYPO3Fluid.

**Closed by NamelessCoder** 2016-07-12 11:07 UTC
